### ISSUE TITLE
Brainstorm Ideas

### ISSUE THREAD

**Issue by cakhigbe** [KSU-DB-2022-VGStore/VideoGameStore#1]
Develop ideas for Video Game Store database project

**Comment by Hunter-Jones** [comment]
I created a quick file with the sql create tables we could use/modify although I don't have push access to upload it

**Comment by cakhigbe** [comment]
> I created a quick file with the sql create tables we could use/modify although I don't have push access to upload it

you should have write access now.

**Comment by Davlittl7** [comment]
I wonder if the website we design should specifically be for the employees to manage and keep track of. Would that make things easier to describe for the functional requirements if we designated this website as something to help keep track of stock and orders from the employee and management's point of view

**Comment by Hunter-Jones** [comment]
I think we should try and make a database
